# Docker Compose

version: '3'

services:
  # services

  currency-exchange:
    container_name: currency-exchange
    image: currency-exchange:0.0.1-SNAPSHOT
    networks:
      - study-spring-cloud-networks
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  currency-exchange-2:
    container_name: currency-exchange-2
    image: currency-exchange:0.0.1-SNAPSHOT
    networks:
      - study-spring-cloud-networks
    restart: on-failure
    ports:
      - "8001:8001"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8001

  currency-conversion:
    container_name: currency-conversion
    image: currency-conversion:0.0.1-SNAPSHOT
    networks:
      - study-spring-cloud-networks
    restart: on-failure
    ports:
      - "8100:8100"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  limit:
    container_name: limit
    image: limit:0.0.1-SNAPSHOT
    networks:
      - study-spring-cloud-networks
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      config:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  # managements
  config:
    container_name: config
    image: config:0.0.1-SNAPSHOT
    networks:
      - study-spring-cloud-networks
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=file:/local-config
    volumes:
      - ./local-config-repo:/local-config
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://config:8888/actuator/health | grep UP || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
  eureka:
    container_name: eureka
    image: eureka:0.0.1-SNAPSHOT
    networks:
      - study-spring-cloud-networks
    restart: on-failure
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://eureka:8761/actuator/health | grep UP || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
  gateway:
    container_name: gateway
    image: gateway:0.0.1-SNAPSHOT
    networks:
      - study-spring-cloud-networks
    restart: on-failure
    ports:
      - "8765:8765"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  study-spring-cloud-networks:
    driver: bridge