spring:
  application:
    name: study-spring-cloud-managements-config
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Projects/study-spring-cloud/local-config-repo
          default-label: main

server:
  port: 8888
