spring:
  application:
    name: managements-config
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Projects/study-spring-cloud/local-config-repo
          default-label: main

server:
  port: 8888

---

spring:
  config:
    activate:
      on-profile: prod

eureka:
  instance:
    hostname: eureka
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
