spring:
  application:
    name: managements-gateway
  config:
    import: optional:configserver:http://config:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8765

---

spring:
  config:
    activate:
      on-profile: prod

eureka:
  instance:
    hostname: eureka
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
