server:
  port: 8100
spring:
  application:
    name: services-currency-conversion
  config:
    import: optional:configserver:http://config:8888
  cloud:
    openfeign:
      client:
        config:
          currency-exchange:
            url: http://localhost:8000
            logger-level: basic

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    openfeign:
      client:
        config:
          currency-exchange:
            url: http://currency-exchange:8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
