server:
  port: 8000
spring:
  application:
    name: services-currency-exchange
  config:
    import: optional:configserver:http://config:8888
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

resilience4j.retry:
  instances:
    sample-circuit:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
resilience4j.ratelimiter:
  instances:
    default:
      limitForPeriod: 2
      limitRefreshPeriod: 10s

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

---

spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"