server:
  port: 8000
spring:
  application:
    name: services-currency-exchange
  config:
    import: optional:configserver:http://config:8888
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password:
  h2:
    console:
      enabled: true
